import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,plName,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch((import.meta as unknown as {env:{BASE_URL:string}}).env.BASE_URL+'models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Nie udało się wczytać katalogu anatomii.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['calcaneal tendon','patella','iliotibial tract','gluteus medius','supraspinatus','intervertebral disk of lumbar vertebra','piriformis','diaphragm','heart','brain'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>plName(c).toLowerCase().includes(term)||c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>plName(a).length-plName(b).length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 /* marcinchlosta.pl: link do struktury (?q=nazwa lub ?id=FMA…, &iso=1 izoluje, &rot=1 obraca) i sterowanie dla nagrań rolek */
 useEffect(()=>{if(!atlas)return;const p=new URLSearchParams(location.search),id=p.get('id'),q=(p.get('q')||'').toLowerCase().trim();const find=(term:string)=>atlas.concepts.find(c=>c.name.toLowerCase()===term||plName(c).toLowerCase()===term)||atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||plName(c).toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length)[0];const c=id?atlas.concepts.find(x=>x.id===id):q?find(q):undefined;if(c){choose(c);if(p.get('iso')==='1'||p.get('rot')==='1')setState(s=>({...s,isolate:p.get('iso')==='1',rotate:p.get('rot')==='1'}));if(p.get('panel')==='0')setDetails(false);}(window as unknown as {__atlas:unknown}).__atlas={find,choose:(term:string)=>{const x=find(term.toLowerCase());if(x)flushSync(()=>choose(x));return !!x;},set:(patch:Partial<SceneState>)=>flushSync(()=>setState(s=>({...s,...patch}))),hidePanel:()=>flushSync(()=>setDetails(false))};},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,pl:p.pl,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERAKTYWNA ANATOMIA</div><h1>Atlas anatomii<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString('pl-PL'):'2234'} modeli 3D <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Panele atlasu"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Szukaj struktury"><Search size={18}/><span>Znajdź strukturę</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="O atlasie" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Warstwy anatomiczne">
   <div className="panel-heading"><span>Układy</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Zamknij układy"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>Wszystko</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Szkielet</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Narządy</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Pokaż tylko: ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Pokaż: ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>Widoczne elementy: {visibleCount.toLocaleString('pl-PL')}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Ukryj wszystko</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Wyszukiwarka struktur"><div className="panel-heading"><span>Znajdź strukturę</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Zamknij wyszukiwanie"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>plName(c)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="np. rzepka, Achilles, stożek rotatorów…" aria-label="Szukaj nazwanych struktur anatomicznych" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>Brak struktur pasujących do wyszukiwania.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{plName(c)}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'element':(c.elements.length%10>=2&&c.elements.length%10<=4&&(c.elements.length%100<10||c.elements.length%100>=20))?'elementy':'elementów'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Pokazuję do 80 wyników. Doprecyzuj nazwę, aby znaleźć mniejsze struktury.':'Zacznij od struktury z listy albo wpisz nazwę po polsku lub łacińsko-angielsku.'}</p></section>}
  <nav className="view-controls glass" aria-label="Sterowanie kamerą">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={['widok ¾','przód','bok','tył'][i]} aria-label={['widok ¾','widok z przodu','widok z boku','widok z tyłu'][i]}><span>{['¾','P','B','T'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Zatrzymaj obrót':'Obracaj ciało'} title="Obrót automatyczny" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Przywróć widok i warstwy" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?plName(chosen).toUpperCase():'WYBRANA STRUKTURA'):state.explode>.95?'WSZYSTKIE ELEMENTY':state.explode>.05?'STRUKTURY ROZSUNIĘTE':'DOROSŁY CZŁOWIEK · MĘŻCZYZNA'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Otwórz warstwy układów"><Layers3 size={20}/><span>Układy</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Rozsuń anatomię</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Złożona</span><span>Każdy element</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Złóż i przywróć"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Przeciągnij, by przesunąć':'Przeciągnij, by obrócić'} <b>·</b> Uszczypnij, by przybliżyć <b>·</b> Dotknij, by sprawdzić</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Źródło i licencja <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Wczytuję anatomię</strong><span>{progress}% · {atlas?.parts.length.toLocaleString('pl-PL')??'2234'} elementów</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Wczytaj ponownie</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMIA'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{plName(chosen)}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">Opis ogólny układu · struktura z bazy BodyParts3D</span>}<div className="structure-meta"><span>Nazwa w atlasie<strong>{chosen?.name}</strong></span><span>Elementy<strong>{state.selected.length.toLocaleString('pl-PL')}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>W skład wchodzą</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{plName(p)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>I jeszcze {selectedParts.length-50} elementów.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">Źródło danych anatomicznych <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Pokaż otoczenie':'Pokaż tylko tę strukturę'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Wyczyść wybór</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">ŹRÓDŁO I ZAKRES</div><SheetTitle className="structure-title">Ciało od środka.</SheetTitle><SheetDescription>Referencyjna anatomia dorosłego mężczyzny z bazy BodyParts3D, po polsku dla pacjentów marcinchlosta.pl.</SheetDescription><div className="about-copy"><p><strong>Mężczyzna · BodyParts3D</strong><br/>2234 modele i 3432 nazwane struktury z referencyjnej anatomii dorosłego mężczyzny.</p><p>Atlas nie zawiera wszystkich struktur ani wariantów budowy — brakuje np. więzadeł krzyżowych i łąkotek. Jedna nazwana struktura może składać się z kilku elementów.</p><p>Kolory i podział na układy ułatwiają oglądanie, geometria jest uproszczona do przeglądarki, a krótkie opisy mają charakter edukacyjny. To pomoc w zrozumieniu budowy ciała, nie narzędzie do diagnozy. Polskie nazwy: tłumaczenie marcinchlosta.pl.</p><h3>Źródło</h3><p>BodyParts3D, © The Database Center for Life Science, licencja CC BY 4.0 (Uznanie autorstwa 4.0 Międzynarodowe). Aplikacja: Human Atlas (licencja MIT), polska wersja dla marcinchlosta.pl.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Licencja danych <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Oryginalna geometria i metadane <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Publikacja źródłowa <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
